# -*- coding: utf-8 -*-
"""final_facemask_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPsBNDXt0TLA4sZvJDGVWy4JZ-qJ8HPX
"""

# Make sure pip is up-to-date and install required libs
!pip install -q --upgrade pip
!pip install -q tensorflow opencv-python-headless lxml matplotlib scikit-learn

!unzip -q archive.zip -d archive

!ls -la archive
!echo "=== with_mask samples ==="
!ls archive/data/with_mask | head -n 10
!echo "=== without_mask samples ==="
!ls archive/data/without_mask | head -n 10

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow:", tf.__version__)

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

# Paths
DATASET_DIR = "archive"
WITH_MASK_DIR = os.path.join(DATASET_DIR, "with_mask")
WITHOUT_MASK_DIR = os.path.join(DATASET_DIR, "without_mask")

# Image size (you can change to 150 or 128 if preferred)
IMG_SIZE = 128

images = []
labels = []

# Label mapping
label_map = {
    "without_mask": 0,
    "with_mask": 1
}

def load_images_from_folder(folder, label):
    for filename in os.listdir(folder):
        img_path = os.path.join(folder, filename)

        # Load image
        img = cv2.imread(img_path)
        if img is None:
            continue  # skip unreadable files

        # Resize
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        # Convert BGR → RGB
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Normalize
        img = img.astype("float32") / 255.0

        images.append(img)
        labels.append(label)

# Corrected paths for loading images
CORRECT_WITH_MASK_DIR = os.path.join(DATASET_DIR, "data", "with_mask")
CORRECT_WITHOUT_MASK_DIR = os.path.join(DATASET_DIR, "data", "without_mask")

# Load both folders using corrected paths
load_images_from_folder(CORRECT_WITH_MASK_DIR, label_map["with_mask"])
load_images_from_folder(CORRECT_WITHOUT_MASK_DIR, label_map["without_mask"])

images = np.array(images)
labels = np.array(labels)

print("Total images:", images.shape)
print("Total labels:", labels.shape)

X_train, X_test, y_train, y_test = train_test_split(
    images, labels,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

print("Training set:", X_train.shape, y_train.shape)
print("Testing set:", X_test.shape, y_test.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))
for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(X_train[i])
    plt.title("Label: " + ("Mask" if y_train[i] == 1 else "No Mask"))
    plt.axis("off")

plt.show()

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),

    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(1, activation='sigmoid')   # Output: 0 or 1
])

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=10,
    batch_size=32
)

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_acc)
print("Test Loss:", test_loss)

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_acc)

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Get filename
image_path = list(uploaded.keys())[0]
print("Uploaded:", image_path)

# Load image
img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Resize same as training
img_resized = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
img_norm = img_resized.astype("float32") / 255.0

# Expand dims → shape: (1, IMG_SIZE, IMG_SIZE, 3)
input_img = np.expand_dims(img_norm, axis=0)

# Prediction
pred = model.predict(input_img)[0][0]   # single value

label = "Mask" if pred >= 0.5 else "No Mask"
confidence = pred if pred >= 0.5 else (1 - pred)

print(f"Prediction: {label} ({confidence*100:.2f}% confidence)")

# Copy image for drawing
output_img = img_rgb.copy()

# Label text
text = f"{label} ({confidence*100:.1f}%)"

# Draw text (cv2.putText wants BGR, so convert)
output_bgr = cv2.cvtColor(output_img, cv2.COLOR_RGB2BGR)
cv2.putText(
    output_bgr,
    text,
    (10, 30),                   # Position
    cv2.FONT_HERSHEY_SIMPLEX,
    1.0,                        # Font scale
    (0, 255, 0) if label=="Mask" else (0, 0, 255),  # Green/Red
    2
)

# Convert back to RGB for display
output_rgb = cv2.cvtColor(output_bgr, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,6))
plt.imshow(output_rgb)
plt.axis("off")
plt.title("Prediction Result")
plt.show()

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Get filename
image_path = list(uploaded.keys())[0]
print("Uploaded:", image_path)
# Load image
img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Resize same as training
img_resized = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
img_norm = img_resized.astype("float32") / 255.0

# Expand dims → shape: (1, IMG_SIZE, IMG_SIZE, 3)
input_img = np.expand_dims(img_norm, axis=0)

# Prediction
pred = model.predict(input_img)[0][0]   # single value

label = "Mask" if pred >= 0.5 else "No Mask"
confidence = pred if pred >= 0.5 else (1 - pred)

print(f"Prediction: {label} ({confidence*100:.2f}% confidence)")
# Copy image for drawing
output_img = img_rgb.copy()

# Label text
text = f"{label} ({confidence*100:.1f}%)"

# Draw text (cv2.putText wants BGR, so convert)
output_bgr = cv2.cvtColor(output_img, cv2.COLOR_RGB2BGR)
cv2.putText(
    output_bgr,
    text,
    (10, 30),                   # Position
    cv2.FONT_HERSHEY_SIMPLEX,
    1.0,                        # Font scale
    (0, 255, 0) if label=="Mask" else (0, 0, 255),  # Green/Red
    2
)

# Convert back to RGB for display
output_rgb = cv2.cvtColor(output_bgr, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,6))
plt.imshow(output_rgb)
plt.axis("off")
plt.title("Prediction Result")
plt.show()

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Get filename
image_path = list(uploaded.keys())[0]
print("Uploaded:", image_path)
# Load image
img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Resize same as training
img_resized = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
img_norm = img_resized.astype("float32") / 255.0

# Expand dims → shape: (1, IMG_SIZE, IMG_SIZE, 3)
input_img = np.expand_dims(img_norm, axis=0)

# Prediction
pred = model.predict(input_img)[0][0]   # single value

label = "Mask" if pred >= 0.5 else "No Mask"
confidence = pred if pred >= 0.5 else (1 - pred)

print(f"Prediction: {label} ({confidence*100:.2f}% confidence)")
# Copy image for drawing
output_img = img_rgb.copy()

# Label text
text = f"{label} ({confidence*100:.1f}%)"

# Draw text (cv2.putText wants BGR, so convert)
output_bgr = cv2.cvtColor(output_img, cv2.COLOR_RGB2BGR)
cv2.putText(
    output_bgr,
    text,
    (10, 30),                   # Position
    cv2.FONT_HERSHEY_SIMPLEX,
    1.0,                        # Font scale
    (0, 255, 0) if label=="Mask" else (0, 0, 255),  # Green/Red
    2
)

# Convert back to RGB for display
output_rgb = cv2.cvtColor(output_bgr, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(6,6))
plt.imshow(output_rgb)
plt.axis("off")
plt.title("Prediction Result")
plt.show()

